apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-api
spec:
  selector:
    matchLabels:
      app: mongodb-api
  template:
    metadata:
      labels:
        app: mongodb-api
    spec:
      containers:
      - name: mongodb-api
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd
