apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
        - name: api-produto
          image: adolfombarros/api-produto:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb-api-service
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWROD
              value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: api-produto-service
spec:
  selector:
    app: api-produto
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
  #  nodePort: 30000
  #type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-produto-ingress 
spec:
  rules:
  - host: api-produto.164.90.253.38.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-produto-service
            port: 
              number: 80
